### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by JIAOJIAYUASD** [Sense-X/UniFormer#35]
when I run the script ' ./exp/mask_rcnn_1x_hybrid_small/run.sh' of uniformer, I get a bug as follows:
Traceback (most recent call last):
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent

                                                                                                                                                                              [56/1124]
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range
    return forward_call(*input, **kwargs)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/models/detectors/two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/models/dense_heads/base_dense_head.py", line 49, in forward_train
    outs = self(x)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/models/dense_heads/anchor_head.py", line 143, in forward
    return multi_apply(self.forward_single, feats)
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mnt/ghome/jiaojiayu/uniformer/object_detection/mmdet/models/dense_heads/rpn_head.py", line 43, in forward_single
    x = self.rpn_conv(x)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/mnt/ghome/jiaojiayu/anaconda3/envs/open-mmlab-2/lib/python3.7/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range

I use the uniformer as the backbone and I don't change the code. Please help me!

**Comment by Andy1621** [comment]
It seems that your `apex` meets some problems. Please see [here](https://blog.csdn.net/starvapour/article/details/122275439) to solve this problem.

**Comment by Andy1621** [comment]
Or you can follow this [PR](https://github.com/NVIDIA/apex/pull/1282) to fix it.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
